version: '3'
services:
  web-nginx:
    image: ${ACR_REGISTRY}/web-nginx
    networks:
      - backend
    ports:
      - "8000:80"

  php-fpm:
    image: ${ACR_REGISTRY}/php-fpm
    networks:
      - backend
    ports:
      - "9000:9000"

networks:
  backend:
