version: '3'
services:
  web-nginx:
    image: example.com/web-nginx
    networks:
      - backend
    ports:
      - "8000:80"

  php-fpm:
    image: example.com/php-fpm
    networks:
      - backend
    ports:
      - "9000:9000"

networks:
  backend:
