version: '3'
services:
  web-nginx:
    image: ghcr.io/dzeyelid/azure-webapp-php-sample/web-nginx
    networks:
      - backend
    ports:
      - "8000:80"

  php-fpm:
    image: ghcr.io/dzeyelid/azure-webapp-php-sample/php-fpm
    networks:
      - backend
    ports:
      - "9000:9000"

networks:
  backend:
